//Steps
if argument0=comL
return true;
if argument0=watrSk
return true;
if argument0=watr1
return true;
if argument0=watr2
return true;
if argument0=watr3
return true;
if argument0=concL
return true;
if argument0=conc1
return true;
if argument0=conc2
return true;
if argument0=conc3
return true;
if argument0=conc4
return true;
if argument0=mtlL
return true;
if argument0=mtl1
return true;
if argument0=mtl2
return true;
if argument0=mtl3
return true;
if argument0=mtl4
return true;
if argument0=woodSk
return true;
if argument0=woodL
return true;
if argument0=wood1
return true;
if argument0=wood2
return true;
if argument0=wood3
return true;
if argument0=wood4
return true;
if argument0=grssSk
return true;
if argument0=grss1
return true;
if argument0=grss2
return true;
if argument0=grss3
return true;
if argument0=grss4
return true;
if argument0=dirtSk
return true;
if argument0=dirt1
return true;
if argument0=dirt2
return true;
if argument0=dirt3
return true;
if argument0=dirt4
return true;
if argument0=skats1
return true;
if argument0=skats2
return true;

// Sonic Voice
if argument0=vcBJump
return true;
if argument0=vcBJump2
return true;
if argument0=vcBAttack
return true;
if argument0=vcBAttack2
return true;
if argument0=vcBBoost
return true;
if argument0=vcBBoost2
return true;
if argument0=vcBHurt
return true;
if argument0=vcBHurt2
return true;
if argument0=vcBHurt3
return true;
if argument0=vcBDie
return true;
if argument0=vcBEdge
return true;
if argument0=vcBFall
return true;

//Shadow Voices
if argument0=vcRJump
return true;
if argument0=vcRJump2
return true;
if argument0=vcRAttack
return true;
if argument0=vcRAttack2
return true;
if argument0=vcRBoost
return true;
if argument0=vcRBoost2
return true;
if argument0=vcRHurt
return true;
if argument0=vcRHurt2
return true;
if argument0=vcRDie
return true;
if argument0=vcREdge
return true;
if argument0=vcRFall
return true;

//Player
if argument0=sndHurt
return true;
if argument0=sndSpinDashCharge
return true;
if argument0=sndSpinDashCharge2
return true;
if argument0=sndSpinDashCharge3
return true;
if argument0=sndSpinDashEnd
return true;
if argument0=sndSpinDashGo
return true;
if argument0=sndSpinDashBoost
return true;
if argument0=sndSkid
return true;
if argument0=sndSkid2
return true;
if argument0=sndBounce
return true;
if argument0=sndCrouchslide
return true;
if argument0=sndSuperTransform
return true;
if argument0=sndJump
return true;
if argument0=sndJumpSpin
return true;
if argument0=sndHomeWave
return true;
if argument0=sndHomeAttack
return true;
if argument0=sndHomeAttack2
return true;
if argument0=sndStomp
return true;
if argument0=sndBreath
return true;
if argument0=sndPoleCatch
return true;

//Moves
if argument0=sndRailLand
return true;
if argument0=sndRingLose
return true;
if argument0=sndLaunchEnter
return true;
if argument0=sndLaunch
return true;
if argument0=sndPoleBounce
return true;
if argument0=sndSpring
return true;
if argument0=sndSpringE
return true;
if argument0=sndSpringHigh
return true;
if argument0=sndDasher
return true;
if argument0=sndAccelerator
return true;
if argument0=sndItemBreak
return true;
if argument0=sndEnemyBreak
return true;
if argument0=sndEnemyBreak2
return true;
if argument0=sndEnemyBreak3
return true;
if argument0=sndGRing
return true;
if argument0=sndRamp
return true;
if argument0=sndSmRamp
return true;
if argument0=sndTrampoline
return true;

//Effects
if argument0=sndSplash
return true;
if argument0=sndSplash2
return true;
if argument0=sndBigSplash
return true;
if argument0=sndHugeSplash
return true;
if argument0=sndBalloon
return true;
if argument0=sndSender
return true;
